-- Tier 3 experimental wishlist: CJ black trench coat (Black S–L only)
-- CJ pid: 1456511646217408512 · default vid Black-M: 1456511646288711681

insert into public.products (
  slug,
  name,
  price_aud,
  compare_at_price_aud,
  category,
  collection_slug,
  description,
  story,
  details,
  sizes,
  featured,
  is_active,
  fulfillment_type,
  supply_source,
  wishlist_goal,
  ships_in_weeks,
  preorder_discount_percent,
  cj_product_id,
  cj_variant_id,
  cj_sku,
  logistic_name,
  from_country_code,
  image_url,
  images
) values (
  'black-double-breasted-trench-coat-14565116',
  'Black Double-Breasted Trench Coat',
  238,
  340,
  'Outerwear',
  'aw26',
  'Long-line black trench with a notched lapel, double-breasted closure, and belt — city layering for AW26.',
  'Tier 3 test — demand vote only. Black colourway. If the waitlist clears, we open a limited preorder via CJ fulfillment (~2 weeks to AU).',
  '["Colour · Black","Silhouette · Double-breasted trench","Length · Mid-long · Over knee","Belt · Detachable tie belt","Fabric · Polyester suiting blend (supplier spec)","Care · Dry clean recommended"]'::jsonb,
  '["S","M","L"]'::jsonb,
  false,
  true,
  'wishlist',
  'cj',
  40,
  2,
  30,
  '1456511646217408512',
  '1456511646288711681',
  'CJFY134290902BY',
  'CJPacket Eub',
  'CN',
  'https://cf.cjdropshipping.com/34c526d6-7b40-4f55-96db-5f4e7cbf2099.jpg',
  '["https://cf.cjdropshipping.com/34c526d6-7b40-4f55-96db-5f4e7cbf2099.jpg","https://cf.cjdropshipping.com/535262bc-f8fc-4388-85b5-70dcb8df4cdf.jpg","https://cf.cjdropshipping.com/a6991392-3e2d-4aca-aec9-1303541d2706.jpg","https://cf.cjdropshipping.com/0787d0b5-3de0-401f-bcec-0d2ccee65b7e.jpg","https://cf.cjdropshipping.com/2e614656-4e51-40d0-87be-738ed1af864b.jpg","https://cf.cjdropshipping.com/b8f99403-05a5-4fcb-9bb0-e3538ff56c47.jpg"]'::jsonb
)
on conflict (slug) do update set
  name = excluded.name,
  price_aud = excluded.price_aud,
  compare_at_price_aud = excluded.compare_at_price_aud,
  description = excluded.description,
  story = excluded.story,
  details = excluded.details,
  sizes = excluded.sizes,
  fulfillment_type = excluded.fulfillment_type,
  supply_source = excluded.supply_source,
  wishlist_goal = excluded.wishlist_goal,
  ships_in_weeks = excluded.ships_in_weeks,
  preorder_discount_percent = excluded.preorder_discount_percent,
  cj_product_id = excluded.cj_product_id,
  cj_variant_id = excluded.cj_variant_id,
  cj_sku = excluded.cj_sku,
  logistic_name = excluded.logistic_name,
  from_country_code = excluded.from_country_code,
  image_url = excluded.image_url,
  images = excluded.images,
  is_active = excluded.is_active,
  updated_at = now();
